# Generated by Django 4.0 on 2021-12-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantao', models.DateField(verbose_name='Dia')),
                ('delegado_dia', models.CharField(max_length=100, verbose_name='Delegado')),
                ('del_apoio_dia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Deleg apoio')),
                ('escriva1_dia', models.CharField(max_length=100, verbose_name='Escrivão')),
                ('escriva2_dia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escriv 2')),
                ('esc_ref_dia', models.CharField(max_length=100, verbose_name='Escriv ref')),
                ('operacional_dia', models.CharField(max_length=100, verbose_name='Operacional')),
                ('oper_ref_dia', models.CharField(max_length=100, verbose_name='Operac ref')),
                ('delegado_noite', models.CharField(max_length=100, verbose_name='Delegado')),
                ('del_apoio_noite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Del apoio')),
                ('escrivao_noite', models.CharField(max_length=100, verbose_name='Escrivão')),
                ('esc_ref_noite', models.CharField(max_length=100, verbose_name='Escriv ref')),
                ('operacional1_noite', models.CharField(max_length=100, verbose_name='Operacional')),
                ('operacional2_noite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operac 2')),
                ('oper_ref_noite', models.CharField(max_length=100, verbose_name='Operac ref')),
            ],
            options={
                'verbose_name_plural': 'Plantões',
            },
        ),
    ]
